# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbb58ad201a52f3beadc1cec1d4a8071197a821bb22dbef09d6cfee962946a71fa56020f8b3b14281d9e1e4e58bd07d29f0ac755e154c81459bd4c68a76231b0

test:
  secret_key_base: 24564d00d0a3dc6a8e5a010256ba4b1d1259ccb98968d500a501cc473ddbe52093b4601302a24598527d4bf3c99b5f686eff006da13c538fdfa5c30ba508c3cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
